name: tp53_analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - biopython
  - pandas
  - matplotlib
  - seaborn
  - numpy
  - scipy
  - r-base
  - r-rmats
  - rpy2
  - snpeff
  - entrez-direct
  - ncbi-entrez-direct
